# /opt/interviewai/docker-compose.yml
version: "3.9"

services:
  backend:
    image: ghcr.io/viviyes/interviewai-backend:latest
    container_name: interviewai-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
